### ISSUE TITLE
Odd behavior after latest grub update

### ISSUE THREAD

**Issue by epic0421** [zeroxoneafour/arch-secureboot#4]
After the grub r380 update, I decided to run `secure-grub-install` again and then updated grub. After rebooting, I noticed that there was an error message that shows up for a split second with shim that says `error: prohibited by secure boot policy.` before going to the grub menu.

Reverting back to grub r334 and performing what I did before, the behavior was back to normal and no error message was shown.

Is this an issue with grub possibly breaking something in the script or is this a wider issue?

**Comment by zeroxoneafour** [comment]
Sorry it took so long to get to this issue, I've been putting off updating for a few days because of my internet.

The error seems to be a problem with grub, and I don't think the script is affected. I updated the modules on my local branch using [this reference from the wiki](https://git.launchpad.net/~ubuntu-core-dev/grub/+git/ubuntu/tree/debian/build-efi-images?h=debian/2.06-2ubuntu12), but it didn't make a difference so the change has not been pushed. I also tried to use all modules installed on the system and preload them into the core, which caused boot failure.

This is a wider issue with grub, but one that is probably intended as a "feature" for more security. There are no updates or references to this issue in the Arch Wiki. The main harmful side effect that came out of this for me was my DPI in boot being screwed up, so unless this fixes itself I'm not looking any farther into it.
